# If you make a change here, you must restart the development server.
# See all possible configure options here: https://jekyllrb.com/docs/configuration/options/


collections:
  members:
    output: true

# Site-wide defaults
# Learn more: https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # Default layout for collections with the name "members" is "member"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
      type: "member"
  # Default layout for all pages and posts
  - scope:
      path: ""
    values:
      layout: "default"
      has_alert: true
      has_footer: true
      has_title: true
      wrap_content: true
  # Default layout for pages
  - scope:
      type: "pages"
    values:
        layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Change the directory where Jekyll will read files
source: ./src/